version: "3.9"

services:
  web:
    image: nginx:alpine
    container_name: forum_web
    ports:
      - "3000:80"
    depends_on:
      - app
    networks:
      - frontend-network
      - backend-network

  app:
    build: .
    container_name: forum_app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/forum_db
      REDIS_URL: redis://redis:6379/0
    networks:
      - backend-network

  sidekiq:
    build: .
    container_name: forum_worker
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/forum_db
      REDIS_URL: redis://redis:6379/0
    networks:
      - backend-network

  db:
    image: postgres:15
    container_name: forum_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forum_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-network

  redis:
    image: redis:7
    container_name: forum_redis
    networks:
      - backend-network

volumes:
  db_data:

networks:
  frontend-network:
    driver: bridge

  backend-network:
    driver: bridge